<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gameplay" nsURI="http://urszeidler.de/shr5/gameplay/1.0" nsPrefix="gameplay">
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionStack">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The execution stack holds the current command and the execution protokoll."/>
    </eAnnotations>
    <eOperations name="redo">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Will execute the current command if there is any."/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentCommand" eType="#//Command"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protocol" lowerBound="1"
        eType="#//ExecutionProtocol" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DamageTest" eSuperTypes="#//ProbeCommand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is the damage test."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="damage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This is the damage the subject has to test agaist."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dv" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This is the armor piercing of the attack."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveDamage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This is thedamage the subject suffers. "/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The basic command interface."/>
    </eAnnotations>
    <eOperations name="redo">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The action method.&#xA;Executes  it self and the sub commands."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="undo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If the command is executed the flag is set to true."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subCommands" upperBound="-1"
        eType="#//Command" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType ../../de.urszeidler.shr5.model/model/shr5.ecore#//ShrDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The game date the command is executed."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cmdCallback" eType="#//CommandCallback"
        transient="true" defaultValueLiteral="" unsettable="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A callback interface for configuring the command."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executing" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This flag is true as long the command is executed."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canExecute" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A flag indication if the command is propper configured."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubjectCommand" abstract="true" eSuperTypes="#//Command">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="THis is the base for command involving subjects."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" lowerBound="1"
        eType="ecore:EClass ../../de.urszeidler.shr5.runtime/model/runtime.ecore#//RuntimeCharacter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkillTestCmd" eSuperTypes="#//ProbeCommand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A skill test."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="skill" lowerBound="1" eType="ecore:EClass ../../de.urszeidler.shr5.model/model/shr5.ecore#//Fertigkeit">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The skill beeing tested."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpposedSkillTestCmd" eSuperTypes="#//SkillTestCmd">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An oppesd test where the object can use the same or another skill."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="ecore:EClass ../../de.urszeidler.shr5.runtime/model/runtime.ecore#//RuntimeCharacter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectSkill" eType="ecore:EClass ../../de.urszeidler.shr5.model/model/shr5.ecore#//Fertigkeit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Initative" eSuperTypes="#//SubjectCommand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is the initive roll."/>
    </eAnnotations>
    <eOperations name="nextPass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="actualPhase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ini" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualIni" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sizeInitative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Si"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionProtocol">
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//Command" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Probe" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The basic probe."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probe" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="THe dice thrown."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="successes" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The successes."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="glitches" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The maximum hits counting for the probe."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probeState" lowerBound="1"
        eType="#//ProbeState" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="probeMods" upperBound="-1"
        eType="#//ProbeMod" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Collects the probe modifactions."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skipTest" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Skips the probe and uses the vaules raw."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProbeCommand" abstract="true" eSuperTypes="#//SubjectCommand #//SuccesTest">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A probe as command."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mods" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The dicepool modifer."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhaseCmd" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CombatTurn" eSuperTypes="#//Command">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="One combat turn."/>
    </eAnnotations>
    <eOperations name="doTurn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="combatants" upperBound="-1"
        eType="ecore:EClass ../../de.urszeidler.shr5.runtime/model/runtime.ecore#//RuntimeCharacter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionPhases" upperBound="-1"
        eType="#//InitativePass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentTurn" eType="#//InitativePass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuccesTest" abstract="true" interface="true"
      eSuperTypes="#//Probe">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is a succes test having a threshold."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thresholds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The number of hit needed to pass the test."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="netHits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The number of hits remains after the threshold."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testState" eType="#//SuccesTestState"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendetSkillTestCmd" eSuperTypes="#//SkillTestCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" lowerBound="1"
        eType="ecore:EDataType ../../de.urszeidler.shr5.model/model/shr5.ecore#//ShrDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intervall" lowerBound="1"
        eType="#//Intervall" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefensTestCmd" eSuperTypes="#//ProbeCommand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The defense test."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attackersHits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The hits to defend against."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuccesTestCmd" eSuperTypes="#//ProbeCommand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A basic succes test."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dicePool" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The dice pool."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitativePass" eSuperTypes="#//SubjectCommand #//PhaseCmd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="turn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sizeInitative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//CommandWrapper" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="freeAction" eType="#//FreeAction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interruptAction" eType="#//InterruptAction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CommandCallback" instanceClassName="de.urszeidler.eclipse.shr5.gameplay.util.CommandCallback"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommandWrapper" abstract="true" eSuperTypes="#//SubjectCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexAction" eSuperTypes="#//CommandWrapper"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleAction" eSuperTypes="#//SubjectCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleActions" eSuperTypes="#//CommandWrapper">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action1" lowerBound="1"
        eType="#//SimpleAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action2" lowerBound="1"
        eType="#//SimpleAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FreeAction" eSuperTypes="#//SubjectCommand"/>
  <eClassifiers xsi:type="ecore:EClass" name="InterruptAction" eSuperTypes="#//SubjectCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iniCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interruptType" eType="#//InterruptType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetFeatureCommand" eSuperTypes="#//Command">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The the value to the ebject in the feature."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeeleAttackCmd" eSuperTypes="#//OpposedSkillTestCmd">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The meele attack."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="weapon" lowerBound="1"
        eType="ecore:EClass ../../de.urszeidler.shr5.model/model/shr5.ecore#//Nahkampfwaffe"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangedAttackCmd" eSuperTypes="#//OpposedSkillTestCmd">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The ranged attack."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modus" eType="ecore:EEnum ../../de.urszeidler.shr5.model/model/shr5.ecore#//FeuerModus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="range" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="weapon" eType="ecore:EClass ../../de.urszeidler.shr5.model/model/shr5.ecore#//AbstaktFernKampfwaffe"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Intervall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantities" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="units" lowerBound="1" eType="#//TimeUnits"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeUnits">
    <eLiterals name="sec"/>
    <eLiterals name="min" value="1"/>
    <eLiterals name="hour" value="2"/>
    <eLiterals name="day" value="3"/>
    <eLiterals name="week" value="4"/>
    <eLiterals name="month" value="5"/>
    <eLiterals name="year" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InterruptType">
    <eLiterals name="block"/>
    <eLiterals name="dodge" value="1"/>
    <eLiterals name="hit_the_dirt" value="2"/>
    <eLiterals name="intercept" value="3"/>
    <eLiterals name="parry" value="4"/>
    <eLiterals name="full_defense" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProbeState">
    <eLiterals name="noGlitch"/>
    <eLiterals name="glitch" value="1"/>
    <eLiterals name="criticalGlitch" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SuccesTestState">
    <eLiterals name="succes" literal="succes"/>
    <eLiterals name="failure" value="1" literal="failure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProbeMod">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines a single probe modificator."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass ../../de.urszeidler.shr5.runtime/model/runtime.ecore#//ExtendetData"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the type of te modificator."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetExtendetData" eSuperTypes="#//Command">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Is used to the the extendet data via command."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataAware" lowerBound="1"
        eType="ecore:EClass ../../de.urszeidler.shr5.runtime/model/runtime.ecore#//AbstractExtendetDataAware">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The target to set the extendet data to."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" eType="ecore:EClass ../../de.urszeidler.shr5.runtime/model/runtime.ecore#//ExtendetData"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
</ecore:EPackage>
