<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="shr5" nsURI="http://urszeidler.de/shr5/1.0" nsPrefix="shr5">
  <eClassifiers xsi:type="ecore:EClass" name="Beschreibbar" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beschreibung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Quelle" abstract="true" interface="true"
      eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="page" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="srcBook" eType="#//SourceBook"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceBook" eSuperTypes="#//Beschreibbar #//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startShrTime" eType="#//ShrDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endShrTime" eType="#//ShrDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ShrDate" instanceClassName="java.util.Date"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstraktPersona" abstract="true" eSuperTypes="#//Beschreibbar #//KoerperlicheAttribute #//SpezielleAttribute #//GeistigeAttribute #//ChrakterLimits">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="konstitutionBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geschicklichkeitBasis"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reaktionBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="staerkeBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charismaBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="willenskraftBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intuitionBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logikBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fertigkeiten" upperBound="-1"
        eType="#//PersonaFertigkeit" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains the fertigkeiten."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fertigkeitsGruppen" upperBound="-1"
        eType="#//PersonaFertigkeitsGruppe" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains the skillgroups."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spezies" lowerBound="1"
        eType="#//Spezies">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Refers the metatyp or species the persona represent."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modManager" lowerBound="1"
        eType="#//ModificationManager" changeable="false" transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Keeps track of the modicators."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gegenstand" eSuperTypes="#//AbstraktGegenstand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A basic item."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kategorie" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stufe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeldWert" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This defines any object having a money value."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wert" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
        changeable="false" volatile="true" transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The calculated money value."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verfuegbarkeit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The availability for the object."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wertValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This is the setable value, it is used to calculate the wert property."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeuerModus">
    <eLiterals name="EM"/>
    <eLiterals name="HM" value="1"/>
    <eLiterals name="SM" value="2"/>
    <eLiterals name="AM" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reichweite" eSuperTypes="#//Beschreibbar #//Identifiable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The range."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kurz" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mittel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weit" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extrem" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributModifikatorWert">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="die Modifikation&#xD;&#xA;&#xD;&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribut" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wert" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiziertes" eType="#//Modifizierbar"
        eOpposite="#//Modifizierbar/mods"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modifizierbar" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mods" upperBound="-1" eType="#//AttributModifikatorWert"
        containment="true" eOpposite="#//AttributModifikatorWert/modifiziertes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KoerperlicheAttribute" abstract="true"
      interface="true" eSuperTypes="#//ModifikatorAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="konstitution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geschicklichkeit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reaktion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="staerke" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpezielleAttribute" abstract="true"
      interface="true" eSuperTypes="#//ModifikatorAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initative" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initativWuerfel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ausweichen" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="essenz" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edgeBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstraktGegenstand" abstract="true"
      eSuperTypes="#//Quelle #//GeldWert #//Beschreibbar #//Modifizierbar #//Anwendbar">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The basic item class."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wifi" eType="#//MatrixDevice"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The optional wifi component of the item."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SchadensTyp">
    <eLiterals name="koerperlich"/>
    <eLiterals name="geistig" value="1"/>
    <eLiterals name="speziell" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstaktFernKampfwaffe" abstract="true"
      eSuperTypes="#//AbstaktWaffe">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reichweite" lowerBound="1"
        eType="#//Reichweite"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstaktWaffe" abstract="true" eSuperTypes="#//AbstraktGegenstand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schadenscode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schadesTyp" eType="#//SchadensTyp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="praezision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durchschlagsKraft" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nahkampfwaffe" eSuperTypes="#//AbstaktWaffe">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reichweite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feuerwaffe" eSuperTypes="#//AbstaktFernKampfwaffe">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="munitionstyp" eType="#//MagazinTyp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modie" upperBound="-1"
        eType="#//FeuerModus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kapazitaet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="erweiterung" upperBound="-1"
        eType="#//FeuwerwaffenErweiterung"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rueckstoss" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="einbau" upperBound="-1"
        eType="#//FernkampfwaffeModifikator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="magazin" unique="false"
        eType="#//Magazin">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This reference holds the current insert magazine."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wurfwaffe" eSuperTypes="#//AbstaktFernKampfwaffe"/>
  <eClassifiers xsi:type="ecore:EEnum" name="MagazinTyp">
    <eLiterals name="Clip"/>
    <eLiterals name="Trommel" value="1"/>
    <eLiterals name="Gurt" value="2"/>
    <eLiterals name="Streifen" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShrList" eSuperTypes="#//Beschreibbar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Projektilwaffe" eSuperTypes="#//AbstaktFernKampfwaffe"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FeuwerwaffenErweiterung">
    <eLiterals name="Lauf"/>
    <eLiterals name="Unten" value="1"/>
    <eLiterals name="Oben" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FertigkeitsGruppe" eSuperTypes="#//Beschreibbar #//Quelle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fertigkeiten" upperBound="-1"
        eType="#//Fertigkeit" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fertigkeit" eSuperTypes="#//Beschreibbar #//Quelle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kategorie" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ausweichen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribut" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spezialisierungen" upperBound="-1"
        eType="#//Spezialisierung" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonaFertigkeit" eSuperTypes="#//Steigerbar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fertigkeit" eType="#//Fertigkeit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spezialisierungen" upperBound="-1"
        eType="#//Spezialisierung"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonaFertigkeitsGruppe" eSuperTypes="#//Steigerbar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gruppe" eType="#//FertigkeitsGruppe"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cyberware" eSuperTypes="#//Koerpermods #//GeldWert">
    <eStructuralFeatures xsi:type="ecore:EReference" name="persona" eType="#//AbstraktPersona"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="einbau" upperBound="-1"
        eType="#//AbstraktGegenstand" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BioWare" eSuperTypes="#//Koerpermods #//GeldWert">
    <eStructuralFeatures xsi:type="ecore:EReference" name="persona" eType="#//AbstraktPersona"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Koerpermods" abstract="true" eSuperTypes="#//AbstraktModifikatoren"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstraktModifikatoren" abstract="true"
      eSuperTypes="#//Beschreibbar #//Modifizierbar #//Quelle"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeistigeAttribute" abstract="true" interface="true"
      eSuperTypes="#//ModifikatorAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charisma" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="willenskraft" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intuition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logik" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MudanPersona" eSuperTypes="#//KoerperPersona"/>
  <eClassifiers xsi:type="ecore:EClass" name="KoerperPersona" abstract="true" eSuperTypes="#//AbstraktPersona #//Panzerung #//PersonaZustand #//BerechneteAttribute">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="We will remove this and store the properties in the abstractPersona."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="koerperMods" upperBound="-1"
        eType="#//Koerpermods" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eigenschaften" upperBound="-1"
        eType="#//PersonaEigenschaft" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zustandKoerperlich" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zustandGeistig" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MagischeMods" abstract="true" eSuperTypes="#//AbstraktModifikatoren"/>
  <eClassifiers xsi:type="ecore:EClass" name="KiKraft" eSuperTypes="#//MagischeMods #//Erlernbar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kraftpunkte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MagischePersona" abstract="true" eSuperTypes="#//KoerperPersona #//BaseMagischePersona">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mentor" eType="#//Schutzgeist"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseMagischePersona" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="magie" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initationen" upperBound="-1"
        eType="#//Initation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="magieBasis" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundFoki" upperBound="-1"
        eType="#//FokusBinding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FernkampfwaffenModifikatoren" abstract="true"
      interface="true" eSuperTypes="#//ModifikatorAttribute">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Modificators for ranged weapons."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="smartgun" eType="#//SmartgunType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rueckstoss" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lasterPointer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schalldaempfer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vergroesserung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sichtverbesserung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sichtverhaeltnisse" abstract="true"
      interface="true" eSuperTypes="#//ModifikatorAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="restlichtverstaerkung"
        eType="#//ModifikatorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infrarot" eType="#//ModifikatorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ultrasound" eType="#//ModifikatorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Spezies" eSuperTypes="#//Beschreibbar #//Modifizierbar #//Quelle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="konstitutionMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geschicklichkeitMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reaktionMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="staerkeMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charismaMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="willenskraftMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intuitionMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logikMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edgeMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="magieMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resonanzMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="essenzMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="konstitutionMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geschicklichkeitMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reaktionMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="staerkeMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charismaMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="willenskraftMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intuitionMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logikMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edgeMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="magieMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resonanzMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="essenzMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="laufen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rennen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sprinten" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="angriff" lowerBound="1"
        eType="#//Nahkampfwaffe" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GegenstandStufen" abstract="true" interface="true"
      eSuperTypes="#//ModifikatorAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="computer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elektronik" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tracing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="antiTracing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="antiProtection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModifikatorType">
    <eLiterals name="Natural"/>
    <eLiterals name="Cyber" value="1"/>
    <eLiterals name="Bio" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SmartgunType">
    <eLiterals name="SmartBrille"/>
    <eLiterals name="SmartGun" value="1"/>
    <eLiterals name="SmatgunII" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KiAdept" eSuperTypes="#//MagischePersona">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kikraft" upperBound="-1"
        eType="#//KiKraft" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Kleidung" eSuperTypes="#//AbstraktGegenstand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the clothes and armor."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruestung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FernkampfwaffeModifikator" eSuperTypes="#//AbstraktModifikatoren">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ep" eType="#//FeuwerwaffenErweiterung"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anwendbar" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Link the item with the skill when using."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fertigkeit" eType="#//Fertigkeit">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the skill."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spezialisierung" eType="#//Spezialisierung">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines a specalism of the skill, for examples for weapons."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonaEigenschaft" eSuperTypes="#//AbstraktModifikatoren #//Erlernbar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="karmaKosten" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProbenModifikatoren" abstract="true"
      interface="true" eSuperTypes="#//ModifikatorAttribute">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Modificators changing a test."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schadenswiederstand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="heilung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Magier" eSuperTypes="#//MagischePersona #//Zauberer #//AstraleProjektion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Zauberer" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="zauber" upperBound="-1"
        eType="#//PersonaZauber" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enzug" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tradition" eType="#//MagischeTradition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gebundeneGeister" upperBound="-1"
        eType="#//GebundenerGeist" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The bound spirits are hold here."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ungebundenerGeist" eType="#//GebundenerGeist"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MysticAdept" eSuperTypes="#//KiAdept #//Zauberer"/>
  <eClassifiers xsi:type="ecore:EClass" name="PersonaZauber" eSuperTypes="#//Erlernbar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stufe" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formel" lowerBound="1"
        eType="#//Zauber"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Zauber" eSuperTypes="#//Beschreibbar #//Quelle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="art" eType="#//ZauberArt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reichweite" eType="#//ZauberReichweite"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schaden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dauer" eType="#//ZauberDauer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entzug" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kategorie" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="merkmale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ZauberArt">
    <eLiterals name="Mana"/>
    <eLiterals name="Physisch" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ZauberReichweite">
    <eLiterals name="Blickfeld"/>
    <eLiterals name="Begrenzt" value="1"/>
    <eLiterals name="Selbst" value="2"/>
    <eLiterals name="Beruehrung" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ZauberDauer">
    <eLiterals name="Sofort"/>
    <eLiterals name="Aufrechterhalten" value="1"/>
    <eLiterals name="Permanent" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChrakterLimits" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the limits."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="koerperlich" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geistig" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sozial" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ModificationManager" instanceClassName="de.urszeidler.eclipse.shr5.ModSetter"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="Panzerung" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="panzer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MagischeTradition">
    <eLiterals name="Hermetisch"/>
    <eLiterals name="Schamanisch" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AspektMagier" eSuperTypes="#//MagischePersona #//Zauberer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aspekt" lowerBound="1"
        eType="#//FertigkeitsGruppe"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AstraleProjektion" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An astral projection."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="astralesLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="astraleKonstitution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="astraleGeschicklichkeit"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="astraleReaktion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="astraleStaerke" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="astraleInitative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="astraleInitativWuerfel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="astralePanzerung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schutzgeist" eSuperTypes="#//MagischeMods">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vorteile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nachteile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Initation" eSuperTypes="#//Steigerbar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="erlernt" eType="#//MetaMagie"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaMagie" eSuperTypes="#//Beschreibbar #//Quelle"/>
  <eClassifiers xsi:type="ecore:EClass" name="CritterKraft" eSuperTypes="#//MagischeMods">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="art" eType="#//ZauberArt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="handlung" eType="#//CritterHandlung"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reichweite" eType="#//CritterReichweite"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dauer" eType="#//CritterDauer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CritterHandlung">
    <eLiterals name="komplex"/>
    <eLiterals name="auto" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CritterReichweite">
    <eLiterals name="blickfeld" literal="blickfeld"/>
    <eLiterals name="beruehrung" value="1"/>
    <eLiterals name="selbst" value="2"/>
    <eLiterals name="speziell" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CritterDauer">
    <eLiterals name="immer"/>
    <eLiterals name="sofort" value="1"/>
    <eLiterals name="aufrechterhalten" value="2"/>
    <eLiterals name="permanent" value="3"/>
    <eLiterals name="speziell" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fahrzeug" abstract="true" eSuperTypes="#//Beschreibbar #//Quelle #//GeldWert #//Anwendbar #//Modifizierbar #//FahrzeugZustand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The basic vehicle type."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="handling" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geschwindigkeit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="beschleunigung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rumpf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pilot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fahrzeugTyp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifizierungen" upperBound="-1"
        eType="#//FahrzeugModifikation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="panzer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weaponMounts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bodenfahrzeug" eSuperTypes="#//PassagierFahrzeug">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A ground vehicle."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="handlingGelaende" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geschwindigkeitGelaende"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PassagierFahrzeug" eSuperTypes="#//Fahrzeug">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A vehicle that can carries passengers."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sitze" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Drohne" eSuperTypes="#//Fahrzeug #//MatrixAttributes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programSlotCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runningPrograms" upperBound="-1"
        eType="#//RiggerProgram">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The running programms are stored here."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storedPrograms" upperBound="-1"
        eType="#//RiggerProgram" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The stored programs defines the programs to choose from when selecting the running programms."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FahrzeugModifikation" abstract="true"
      eSuperTypes="#//Beschreibbar #//Quelle #//GeldWert"/>
  <eClassifiers xsi:type="ecore:EClass" name="Technomancer" eSuperTypes="#//KoerperPersona #//ResonanzPersona">
    <eStructuralFeatures xsi:type="ecore:EReference" name="complexForms" upperBound="-1"
        eType="#//PersonaKomplexForm" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="echos" upperBound="-1"
        eType="#//Echo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResonanzPersona" abstract="true" interface="true"
      eSuperTypes="#//ActiveMatixDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resonanz" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resonanzBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KomplexeForm" eSuperTypes="#//Quelle #//Beschreibbar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ziel" eType="#//ResonanzZiel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dauer" eType="#//ZauberDauer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schwund" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonaKomplexForm" eSuperTypes="#//Erlernbar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="form" lowerBound="1" eType="#//KomplexeForm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stufe" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ResonanzZiel">
    <eLiterals name="datei"/>
    <eLiterals name="geraet" value="1"/>
    <eLiterals name="selbst" value="2"/>
    <eLiterals name="persona" value="3"/>
    <eLiterals name="sprite" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sprite" eSuperTypes="#//ResonanzPersona #//Beschreibbar #//Quelle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stufe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angriffMod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schleicherMod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datenverarbeitungMod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firewallMod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initativeMod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Echo" eSuperTypes="#//AbstraktModifikatoren"/>
  <eClassifiers xsi:type="ecore:EClass" name="Vertrag" eSuperTypes="#//Beschreibbar #//Quelle #//GeldWert"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lifestyle" eSuperTypes="#//IntervallVertrag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//LifestyleOption" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owned" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wissensfertigkeit" eSuperTypes="#//Fertigkeit"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sprachfertigkeit" eSuperTypes="#//Wissensfertigkeit"/>
  <eClassifiers xsi:type="ecore:EClass" name="PersonaZustand" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zustandKoerperlichMax"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zustandGeistigMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zustandGrenze" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Critter" eSuperTypes="#//Spezies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="powers" upperBound="-1"
        eType="#//CritterKraft" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntervallVertrag" abstract="true" eSuperTypes="#//Vertrag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faelligkeitsIntervall"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sin" eSuperTypes="#//Fakeable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lizenz" eSuperTypes="#//Fakeable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lizenGegenstand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lizenzTraeger" lowerBound="1"
        eType="#//Sin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fakeable" abstract="true" eSuperTypes="#//Vertrag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stufe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gefaelscht" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Steigerbar" abstract="true" interface="true"
      eSuperTypes="#//Erlernbar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stufe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Erlernbar" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Tagging interface for all elements part of character advacements."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Credstick" eSuperTypes="#//AbstraktGegenstand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A credstick can hold money and has a transactions log."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transactionlog" upperBound="-1"
        eType="#//CredstickTransaction" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The sum of the entries is the current wertValue."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Menge" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This interface is used to define items coming in great numbers like amunition and others."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anzahl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The current count of items."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="proAnzahl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the number of items for the cost, if the element is a GeldWert."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Munition" eSuperTypes="#//AbstraktGegenstand #//Menge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="damageType" eType="#//SchadensTyp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="damageMod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="armorMod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Reichweite"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModifikatorAttribute" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Modificator attributes are used to define additional aspects."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GebundenerGeist">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dienste" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geist" lowerBound="1" eType="#//Geist"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StufenPersona" abstract="true" interface="true"
      eSuperTypes="#//Quelle #//SpezielleAttribute #//GeistigeAttribute #//KoerperlicheAttribute #//Beschreibbar #//ChrakterLimits #//Panzerung">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The rating defines the attribute values."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stufe" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="skillGroups" upperBound="-1"
        eType="#//FertigkeitsGruppe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="skills" upperBound="-1"
        eType="#//Fertigkeit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Geist" eSuperTypes="#//StufenPersona #//AstraleProjektion">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This defines a spirit."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="konstitutionBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geschicklichkeitBasis"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reaktionBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="staerkeBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charismaBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="willenskraftBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intuitionBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logikBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="powers" upperBound="-1"
        eType="#//CritterKraft" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionalPowers" upperBound="-1"
        eType="#//CritterKraft" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localizations" upperBound="-1"
        eType="#//Localization" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CredstickTransaction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is an entry in the log."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="#//ShrDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Spezialisierung" eSuperTypes="#//Beschreibbar #//Quelle #//Erlernbar"/>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixAttributes" abstract="true" interface="true"
      eSuperTypes="#//MatixConditionMonitor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the interface for all passive matix devices."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="geraetestufe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firewall" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datenverarbeitung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentModus" eType="#//InterfaceModus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActiveMatixDevice" abstract="true" interface="true"
      eSuperTypes="#//MatrixAttributes">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="All active Matrix defice are defined thou this interface."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="angriff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schleicher" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Commlink" eSuperTypes="#//AbstractMatrixDevice">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This defines the complink."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storedPrograms" upperBound="-1"
        eType="#//BasicProgram" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The stored programs defines the programs to choose from when selecting the running programms."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatixConditionMonitor" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matrixZustandMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cyberdeck" eSuperTypes="#//AbstractMatrixDevice #//MatrixDevice #//ActiveMatixDevice">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This defines the cyberdeck."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programSlots" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The number probrams the deck can run concuntrly."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute1" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute2" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute3" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute4" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="4"
        upperBound="4" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains the value attribues for the matrix attributes. Index 0 firewall,1datenverarbeitung, 2 angriff and 3 schleicher."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storedPrograms" upperBound="-1"
        eType="#//MatrixProgram" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runningPrograms" upperBound="-1"
        eType="#//MatrixProgram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InterfaceModus">
    <eLiterals name="augmentedReality"/>
    <eLiterals name="coldSim" value="1"/>
    <eLiterals name="hotSim" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareAgent" eSuperTypes="#//MatrixProgram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rating" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Host" eSuperTypes="#//Beschreibbar #//MatrixDevice #//ActiveMatixDevice">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This defines a host."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostRating" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseFirewall" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseDatenverarbeitung"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseAngriff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseSchleicher" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CyberwareModifikatioren" abstract="true"
      interface="true" eSuperTypes="#//ModifikatorAttribute">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Collects the cyberware related modificators."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directNeuralInterface"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defnies a DNI."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="universalDataConnector"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the UDC."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlRig" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines a rigger controll. The value is the grade."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simRig" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="riggerInterface" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RiggerCommandConsole" eSuperTypes="#//AbstractMatrixDevice">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines rigger consoles."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rauschunterdrueckung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zugriff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datenverarbeitungBasis"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firewallBasis" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zugriffBasis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This value is for the zugriff feature, the rauchunter. is calculated as deviceRating-zugriffBasis."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storedPrograms" upperBound="-1"
        eType="#//RiggerProgram" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runningPrograms" upperBound="-1"
        eType="#//RiggerProgram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutoSoft" eSuperTypes="#//RiggerProgram">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the software for drones."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rating" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="skill" eType="#//Fertigkeit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="weapon" eType="#//AbstaktWaffe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//Drohne"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Software" abstract="true" interface="true"
      eSuperTypes="#//GeldWert #//Beschreibbar #//Quelle"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ProgramType">
    <eLiterals name="defaultSoft" literal="defaultSoft"/>
    <eLiterals name="dataSoft" value="1"/>
    <eLiterals name="shopSoft" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixProgram" abstract="true" interface="true"
      eSuperTypes="#//Software"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tutorsoft" eSuperTypes="#//BasicProgram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rating" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="skill" lowerBound="1" eType="#//Fertigkeit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkillSoft" eSuperTypes="#//Software">
    <eStructuralFeatures xsi:type="ecore:EReference" name="skill" lowerBound="1" eType="#//Fertigkeit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rating" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FahrzeugZustand" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zustandMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonalAreaNetwork">
    <eStructuralFeatures xsi:type="ecore:EReference" name="slaves" upperBound="-1"
        eType="#//MatrixDevice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="master" lowerBound="1"
        eType="#//MatrixDevice" eOpposite="#//MatrixDevice/pan"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slaveMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicProgram" abstract="true" eSuperTypes="#//Software"/>
  <eClassifiers xsi:type="ecore:EClass" name="Datasoft" eSuperTypes="#//BasicProgram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="skill" lowerBound="1" eType="#//Wissensfertigkeit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMatrixDevice" abstract="true"
      interface="true" eSuperTypes="#//AbstraktGegenstand #//MatrixDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceRating" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConsumerSoft" eSuperTypes="#//BasicProgram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ProgramType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RiggerProgram" abstract="true" interface="true"
      eSuperTypes="#//Software"/>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixDevice" abstract="true" interface="true"
      eSuperTypes="#//MatrixAttributes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pan" eType="#//PersonalAreaNetwork"
        containment="true" eOpposite="#//PersonalAreaNetwork/master"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommonProgram" eSuperTypes="#//MatrixProgram #//RiggerProgram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programType" eType="#//MatrixProgramType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MatrixProgramType">
    <eLiterals name="defaultProgram"/>
    <eLiterals name="hackingProgram" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeaponMount" eSuperTypes="#//FahrzeugModifikation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="weapon" lowerBound="1"
        eType="#//AbstaktWaffe" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LifestyleOption" eSuperTypes="#//Beschreibbar #//Quelle #//GeldWert"/>
  <eClassifiers xsi:type="ecore:EClass" name="PercentLifestyleOption" eSuperTypes="#//LifestyleOption">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The werValue ist interpreted as percent value so the wert is wertContainer * wertValue/100."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Localization">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="local" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="page" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BerechneteAttribute" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Contains the calculatetd derived attributes like composure. Attribute only testst for example."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errinerungsvermoegen" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The memory."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="menschenkenntnis" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Judge Intentions."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selbstbeherrschung" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Composure."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MagischeStufe" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is the basic magical rating class."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stufe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fokus" abstract="true" interface="true"
      eSuperTypes="#//MagischeStufe #//Erlernbar">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The fokus has binding costs."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindungskosten" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The memory."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstraktFokus" abstract="true" eSuperTypes="#//Fokus #//AbstraktGegenstand"/>
  <eClassifiers xsi:type="ecore:EClass" name="QiFokus" eSuperTypes="#//AbstraktFokus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="power" lowerBound="1" eType="#//KiKraft"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WaffenFokus" eSuperTypes="#//Nahkampfwaffe #//Fokus"/>
  <eClassifiers xsi:type="ecore:EClass" name="MagieFokus" eSuperTypes="#//AbstraktFokus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindungsFaktor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FokusBinding">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This represent an binding to a fokus."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fokus" lowerBound="1" eType="#//Fokus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Substance" abstract="true" eSuperTypes="#//Beschreibbar #//Quelle #//GeldWert #//Menge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vector" eType="#//SubstanceVector"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SubstanceVector">
    <eLiterals name="contact"/>
    <eLiterals name="inhalation" value="1"/>
    <eLiterals name="ingestion" value="2"/>
    <eLiterals name="injection" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Toxin" eSuperTypes="#//Substance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="power" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="penetration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effect" upperBound="-1"
        eType="#//SubstanceEffect"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Drug" eSuperTypes="#//Substance #//Modifizierbar">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addictionType" eType="#//AddictionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SubstanceEffect">
    <eLiterals name="disorientation"/>
    <eLiterals name="nausea" value="1"/>
    <eLiterals name="paralysis" value="2"/>
    <eLiterals name="stunDamage" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AddictionType">
    <eLiterals name="psychological"/>
    <eLiterals name="physiological" value="1"/>
    <eLiterals name="both" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Magazin" eSuperTypes="#//AbstraktGegenstand">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is the bullet container (clip) for a fw."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Feuerwaffe">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The type defines which weapon this magazin can be used with."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bullets" unique="false"
        upperBound="-1" eType="#//Munition">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This reference holds the current loaded amuntition, when used the first element should be removed."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultWifi" eSuperTypes="#//AbstractMatrixDevice"/>
</ecore:EPackage>
