/**
 */
package de.urszeidler.eclipse.shr5.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import de.urszeidler.eclipse.shr5.util.Shr5AdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class Shr5ItemProviderAdapterFactory extends Shr5AdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
     * This keeps track of the root adapter factory that delegates to this adapter factory.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
     * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
     * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
     * This constructs an instance.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	public Shr5ItemProviderAdapterFactory() {
        supportedTypes.add(IEditingDomainItemProvider.class);
        supportedTypes.add(IStructuredItemContentProvider.class);
        supportedTypes.add(ITreeItemContentProvider.class);
        supportedTypes.add(IItemLabelProvider.class);
        supportedTypes.add(IItemPropertySource.class);
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.SourceBook} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected SourceBookItemProvider sourceBookItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.SourceBook}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createSourceBookAdapter() {
        if (sourceBookItemProvider == null) {
            sourceBookItemProvider = new SourceBookItemProvider(this);
        }

        return sourceBookItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Gegenstand} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected GegenstandItemProvider gegenstandItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Gegenstand}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createGegenstandAdapter() {
        if (gegenstandItemProvider == null) {
            gegenstandItemProvider = new GegenstandItemProvider(this);
        }

        return gegenstandItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Reichweite} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected ReichweiteItemProvider reichweiteItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Reichweite}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createReichweiteAdapter() {
        if (reichweiteItemProvider == null) {
            reichweiteItemProvider = new ReichweiteItemProvider(this);
        }

        return reichweiteItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.AttributModifikatorWert} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected AttributModifikatorWertItemProvider attributModifikatorWertItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.AttributModifikatorWert}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createAttributModifikatorWertAdapter() {
        if (attributModifikatorWertItemProvider == null) {
            attributModifikatorWertItemProvider = new AttributModifikatorWertItemProvider(this);
        }

        return attributModifikatorWertItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Nahkampfwaffe} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected NahkampfwaffeItemProvider nahkampfwaffeItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Nahkampfwaffe}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createNahkampfwaffeAdapter() {
        if (nahkampfwaffeItemProvider == null) {
            nahkampfwaffeItemProvider = new NahkampfwaffeItemProvider(this);
        }

        return nahkampfwaffeItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Feuerwaffe} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected FeuerwaffeItemProvider feuerwaffeItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Feuerwaffe}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createFeuerwaffeAdapter() {
        if (feuerwaffeItemProvider == null) {
            feuerwaffeItemProvider = new FeuerwaffeItemProvider(this);
        }

        return feuerwaffeItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Wurfwaffe} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected WurfwaffeItemProvider wurfwaffeItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Wurfwaffe}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createWurfwaffeAdapter() {
        if (wurfwaffeItemProvider == null) {
            wurfwaffeItemProvider = new WurfwaffeItemProvider(this);
        }

        return wurfwaffeItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.ShrList} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected ShrListItemProvider shrListItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.ShrList}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createShrListAdapter() {
        if (shrListItemProvider == null) {
            shrListItemProvider = new ShrListItemProvider(this);
        }

        return shrListItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Projektilwaffe} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected ProjektilwaffeItemProvider projektilwaffeItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Projektilwaffe}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createProjektilwaffeAdapter() {
        if (projektilwaffeItemProvider == null) {
            projektilwaffeItemProvider = new ProjektilwaffeItemProvider(this);
        }

        return projektilwaffeItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.FertigkeitsGruppe} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected FertigkeitsGruppeItemProvider fertigkeitsGruppeItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.FertigkeitsGruppe}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createFertigkeitsGruppeAdapter() {
        if (fertigkeitsGruppeItemProvider == null) {
            fertigkeitsGruppeItemProvider = new FertigkeitsGruppeItemProvider(this);
        }

        return fertigkeitsGruppeItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Fertigkeit} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected FertigkeitItemProvider fertigkeitItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Fertigkeit}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createFertigkeitAdapter() {
        if (fertigkeitItemProvider == null) {
            fertigkeitItemProvider = new FertigkeitItemProvider(this);
        }

        return fertigkeitItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.PersonaFertigkeit} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected PersonaFertigkeitItemProvider personaFertigkeitItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.PersonaFertigkeit}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createPersonaFertigkeitAdapter() {
        if (personaFertigkeitItemProvider == null) {
            personaFertigkeitItemProvider = new PersonaFertigkeitItemProvider(this);
        }

        return personaFertigkeitItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.PersonaFertigkeitsGruppe} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected PersonaFertigkeitsGruppeItemProvider personaFertigkeitsGruppeItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.PersonaFertigkeitsGruppe}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createPersonaFertigkeitsGruppeAdapter() {
        if (personaFertigkeitsGruppeItemProvider == null) {
            personaFertigkeitsGruppeItemProvider = new PersonaFertigkeitsGruppeItemProvider(this);
        }

        return personaFertigkeitsGruppeItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Cyberware} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected CyberwareItemProvider cyberwareItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Cyberware}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createCyberwareAdapter() {
        if (cyberwareItemProvider == null) {
            cyberwareItemProvider = new CyberwareItemProvider(this);
        }

        return cyberwareItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.BioWare} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected BioWareItemProvider bioWareItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.BioWare}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createBioWareAdapter() {
        if (bioWareItemProvider == null) {
            bioWareItemProvider = new BioWareItemProvider(this);
        }

        return bioWareItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.MudanPersona} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected MudanPersonaItemProvider mudanPersonaItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.MudanPersona}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createMudanPersonaAdapter() {
        if (mudanPersonaItemProvider == null) {
            mudanPersonaItemProvider = new MudanPersonaItemProvider(this);
        }

        return mudanPersonaItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.KiKraft} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected KiKraftItemProvider kiKraftItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.KiKraft}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createKiKraftAdapter() {
        if (kiKraftItemProvider == null) {
            kiKraftItemProvider = new KiKraftItemProvider(this);
        }

        return kiKraftItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Spezies} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected SpeziesItemProvider speziesItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Spezies}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createSpeziesAdapter() {
        if (speziesItemProvider == null) {
            speziesItemProvider = new SpeziesItemProvider(this);
        }

        return speziesItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.KiAdept} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected KiAdeptItemProvider kiAdeptItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.KiAdept}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createKiAdeptAdapter() {
        if (kiAdeptItemProvider == null) {
            kiAdeptItemProvider = new KiAdeptItemProvider(this);
        }

        return kiAdeptItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Kleidung} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected KleidungItemProvider kleidungItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Kleidung}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createKleidungAdapter() {
        if (kleidungItemProvider == null) {
            kleidungItemProvider = new KleidungItemProvider(this);
        }

        return kleidungItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.FernkampfwaffeModifikator} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected FernkampfwaffeModifikatorItemProvider fernkampfwaffeModifikatorItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.FernkampfwaffeModifikator}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createFernkampfwaffeModifikatorAdapter() {
        if (fernkampfwaffeModifikatorItemProvider == null) {
            fernkampfwaffeModifikatorItemProvider = new FernkampfwaffeModifikatorItemProvider(this);
        }

        return fernkampfwaffeModifikatorItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.PersonaEigenschaft} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected PersonaEigenschaftItemProvider personaEigenschaftItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.PersonaEigenschaft}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createPersonaEigenschaftAdapter() {
        if (personaEigenschaftItemProvider == null) {
            personaEigenschaftItemProvider = new PersonaEigenschaftItemProvider(this);
        }

        return personaEigenschaftItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Magier} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected MagierItemProvider magierItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Magier}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createMagierAdapter() {
        if (magierItemProvider == null) {
            magierItemProvider = new MagierItemProvider(this);
        }

        return magierItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.MysticAdept} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected MysticAdeptItemProvider mysticAdeptItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.MysticAdept}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createMysticAdeptAdapter() {
        if (mysticAdeptItemProvider == null) {
            mysticAdeptItemProvider = new MysticAdeptItemProvider(this);
        }

        return mysticAdeptItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.PersonaZauber} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected PersonaZauberItemProvider personaZauberItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.PersonaZauber}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createPersonaZauberAdapter() {
        if (personaZauberItemProvider == null) {
            personaZauberItemProvider = new PersonaZauberItemProvider(this);
        }

        return personaZauberItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Zauber} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected ZauberItemProvider zauberItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Zauber}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createZauberAdapter() {
        if (zauberItemProvider == null) {
            zauberItemProvider = new ZauberItemProvider(this);
        }

        return zauberItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.AspektMagier} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected AspektMagierItemProvider aspektMagierItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.AspektMagier}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createAspektMagierAdapter() {
        if (aspektMagierItemProvider == null) {
            aspektMagierItemProvider = new AspektMagierItemProvider(this);
        }

        return aspektMagierItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Schutzgeist} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected SchutzgeistItemProvider schutzgeistItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Schutzgeist}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createSchutzgeistAdapter() {
        if (schutzgeistItemProvider == null) {
            schutzgeistItemProvider = new SchutzgeistItemProvider(this);
        }

        return schutzgeistItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Initation} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected InitationItemProvider initationItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Initation}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createInitationAdapter() {
        if (initationItemProvider == null) {
            initationItemProvider = new InitationItemProvider(this);
        }

        return initationItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.MetaMagie} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected MetaMagieItemProvider metaMagieItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.MetaMagie}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createMetaMagieAdapter() {
        if (metaMagieItemProvider == null) {
            metaMagieItemProvider = new MetaMagieItemProvider(this);
        }

        return metaMagieItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.CritterKraft} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected CritterKraftItemProvider critterKraftItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.CritterKraft}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createCritterKraftAdapter() {
        if (critterKraftItemProvider == null) {
            critterKraftItemProvider = new CritterKraftItemProvider(this);
        }

        return critterKraftItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Bodenfahrzeug} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected BodenfahrzeugItemProvider bodenfahrzeugItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Bodenfahrzeug}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createBodenfahrzeugAdapter() {
        if (bodenfahrzeugItemProvider == null) {
            bodenfahrzeugItemProvider = new BodenfahrzeugItemProvider(this);
        }

        return bodenfahrzeugItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.PassagierFahrzeug} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected PassagierFahrzeugItemProvider passagierFahrzeugItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.PassagierFahrzeug}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createPassagierFahrzeugAdapter() {
        if (passagierFahrzeugItemProvider == null) {
            passagierFahrzeugItemProvider = new PassagierFahrzeugItemProvider(this);
        }

        return passagierFahrzeugItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Drohne} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected DrohneItemProvider drohneItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Drohne}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createDrohneAdapter() {
        if (drohneItemProvider == null) {
            drohneItemProvider = new DrohneItemProvider(this);
        }

        return drohneItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.FahrzeugModifikation} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected FahrzeugModifikationItemProvider fahrzeugModifikationItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.FahrzeugModifikation}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createFahrzeugModifikationAdapter() {
        if (fahrzeugModifikationItemProvider == null) {
            fahrzeugModifikationItemProvider = new FahrzeugModifikationItemProvider(this);
        }

        return fahrzeugModifikationItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Technomancer} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected TechnomancerItemProvider technomancerItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Technomancer}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createTechnomancerAdapter() {
        if (technomancerItemProvider == null) {
            technomancerItemProvider = new TechnomancerItemProvider(this);
        }

        return technomancerItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.KomplexeForm} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected KomplexeFormItemProvider komplexeFormItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.KomplexeForm}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createKomplexeFormAdapter() {
        if (komplexeFormItemProvider == null) {
            komplexeFormItemProvider = new KomplexeFormItemProvider(this);
        }

        return komplexeFormItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.PersonaKomplexForm} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected PersonaKomplexFormItemProvider personaKomplexFormItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.PersonaKomplexForm}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createPersonaKomplexFormAdapter() {
        if (personaKomplexFormItemProvider == null) {
            personaKomplexFormItemProvider = new PersonaKomplexFormItemProvider(this);
        }

        return personaKomplexFormItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Sprite} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected SpriteItemProvider spriteItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Sprite}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createSpriteAdapter() {
        if (spriteItemProvider == null) {
            spriteItemProvider = new SpriteItemProvider(this);
        }

        return spriteItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Echo} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected EchoItemProvider echoItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Echo}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createEchoAdapter() {
        if (echoItemProvider == null) {
            echoItemProvider = new EchoItemProvider(this);
        }

        return echoItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Vertrag} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected VertragItemProvider vertragItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Vertrag}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createVertragAdapter() {
        if (vertragItemProvider == null) {
            vertragItemProvider = new VertragItemProvider(this);
        }

        return vertragItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Lifestyle} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected LifestyleItemProvider lifestyleItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Lifestyle}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createLifestyleAdapter() {
        if (lifestyleItemProvider == null) {
            lifestyleItemProvider = new LifestyleItemProvider(this);
        }

        return lifestyleItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Wissensfertigkeit} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected WissensfertigkeitItemProvider wissensfertigkeitItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Wissensfertigkeit}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createWissensfertigkeitAdapter() {
        if (wissensfertigkeitItemProvider == null) {
            wissensfertigkeitItemProvider = new WissensfertigkeitItemProvider(this);
        }

        return wissensfertigkeitItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Sprachfertigkeit} instances.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	protected SprachfertigkeitItemProvider sprachfertigkeitItemProvider;

	/**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Sprachfertigkeit}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter createSprachfertigkeitAdapter() {
        if (sprachfertigkeitItemProvider == null) {
            sprachfertigkeitItemProvider = new SprachfertigkeitItemProvider(this);
        }

        return sprachfertigkeitItemProvider;
    }

	/**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Critter} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CritterItemProvider critterItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Critter}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createCritterAdapter() {
        if (critterItemProvider == null) {
            critterItemProvider = new CritterItemProvider(this);
        }

        return critterItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Sin} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SinItemProvider sinItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Sin}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSinAdapter() {
        if (sinItemProvider == null) {
            sinItemProvider = new SinItemProvider(this);
        }

        return sinItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Lizenz} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LizenzItemProvider lizenzItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Lizenz}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createLizenzAdapter() {
        if (lizenzItemProvider == null) {
            lizenzItemProvider = new LizenzItemProvider(this);
        }

        return lizenzItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Credstick} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CredstickItemProvider credstickItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Credstick}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createCredstickAdapter() {
        if (credstickItemProvider == null) {
            credstickItemProvider = new CredstickItemProvider(this);
        }

        return credstickItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Munition} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected MunitionItemProvider munitionItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Munition}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createMunitionAdapter() {
        if (munitionItemProvider == null) {
            munitionItemProvider = new MunitionItemProvider(this);
        }

        return munitionItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.GebundenerGeist} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected GebundenerGeistItemProvider gebundenerGeistItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.GebundenerGeist}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createGebundenerGeistAdapter() {
        if (gebundenerGeistItemProvider == null) {
            gebundenerGeistItemProvider = new GebundenerGeistItemProvider(this);
        }

        return gebundenerGeistItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Geist} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected GeistItemProvider geistItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Geist}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createGeistAdapter() {
        if (geistItemProvider == null) {
            geistItemProvider = new GeistItemProvider(this);
        }

        return geistItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.CredstickTransaction} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CredstickTransactionItemProvider credstickTransactionItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.CredstickTransaction}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createCredstickTransactionAdapter() {
        if (credstickTransactionItemProvider == null) {
            credstickTransactionItemProvider = new CredstickTransactionItemProvider(this);
        }

        return credstickTransactionItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Spezialisierung} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SpezialisierungItemProvider spezialisierungItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Spezialisierung}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSpezialisierungAdapter() {
        if (spezialisierungItemProvider == null) {
            spezialisierungItemProvider = new SpezialisierungItemProvider(this);
        }

        return spezialisierungItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Commlink} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CommlinkItemProvider commlinkItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Commlink}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createCommlinkAdapter() {
        if (commlinkItemProvider == null) {
            commlinkItemProvider = new CommlinkItemProvider(this);
        }

        return commlinkItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Cyberdeck} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CyberdeckItemProvider cyberdeckItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Cyberdeck}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createCyberdeckAdapter() {
        if (cyberdeckItemProvider == null) {
            cyberdeckItemProvider = new CyberdeckItemProvider(this);
        }

        return cyberdeckItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Program} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ProgramItemProvider programItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Program}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createProgramAdapter() {
        if (programItemProvider == null) {
            programItemProvider = new ProgramItemProvider(this);
        }

        return programItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.SoftwareAgent} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SoftwareAgentItemProvider softwareAgentItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.SoftwareAgent}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSoftwareAgentAdapter() {
        if (softwareAgentItemProvider == null) {
            softwareAgentItemProvider = new SoftwareAgentItemProvider(this);
        }

        return softwareAgentItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.Host} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected HostItemProvider hostItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.Host}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createHostAdapter() {
        if (hostItemProvider == null) {
            hostItemProvider = new HostItemProvider(this);
        }

        return hostItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link de.urszeidler.eclipse.shr5.RiggerCommandConsole} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected RiggerCommandConsoleItemProvider riggerCommandConsoleItemProvider;

    /**
     * This creates an adapter for a {@link de.urszeidler.eclipse.shr5.RiggerCommandConsole}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createRiggerCommandConsoleAdapter() {
        if (riggerCommandConsoleItemProvider == null) {
            riggerCommandConsoleItemProvider = new RiggerCommandConsoleItemProvider(this);
        }

        return riggerCommandConsoleItemProvider;
    }

    /**
     * This returns the root adapter factory that contains this factory.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	public ComposeableAdapterFactory getRootAdapterFactory() {
        return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
    }

	/**
     * This sets the composed adapter factory that contains this factory.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
        this.parentAdapterFactory = parentAdapterFactory;
    }

	/**
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public boolean isFactoryForType(Object type) {
        return supportedTypes.contains(type) || super.isFactoryForType(type);
    }

	/**
     * This implementation substitutes the factory itself as the key for the adapter.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
        return super.adapt(notifier, this);
    }

	/**
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	@Override
	public Object adapt(Object object, Object type) {
        if (isFactoryForType(type)) {
            Object adapter = super.adapt(object, type);
            if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
                return adapter;
            }
        }

        return null;
    }

	/**
     * This adds a listener.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	public void addListener(INotifyChangedListener notifyChangedListener) {
        changeNotifier.addListener(notifyChangedListener);
    }

	/**
     * This removes a listener.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
        changeNotifier.removeListener(notifyChangedListener);
    }

	/**
     * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	public void fireNotifyChanged(Notification notification) {
        changeNotifier.fireNotifyChanged(notification);

        if (parentAdapterFactory != null) {
            parentAdapterFactory.fireNotifyChanged(notification);
        }
    }

	/**
     * This disposes all of the item providers created by this factory. 
     * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
     * @generated
     */
	public void dispose() {
        if (sourceBookItemProvider != null) sourceBookItemProvider.dispose();
        if (gegenstandItemProvider != null) gegenstandItemProvider.dispose();
        if (reichweiteItemProvider != null) reichweiteItemProvider.dispose();
        if (attributModifikatorWertItemProvider != null) attributModifikatorWertItemProvider.dispose();
        if (nahkampfwaffeItemProvider != null) nahkampfwaffeItemProvider.dispose();
        if (feuerwaffeItemProvider != null) feuerwaffeItemProvider.dispose();
        if (wurfwaffeItemProvider != null) wurfwaffeItemProvider.dispose();
        if (shrListItemProvider != null) shrListItemProvider.dispose();
        if (projektilwaffeItemProvider != null) projektilwaffeItemProvider.dispose();
        if (fertigkeitsGruppeItemProvider != null) fertigkeitsGruppeItemProvider.dispose();
        if (fertigkeitItemProvider != null) fertigkeitItemProvider.dispose();
        if (personaFertigkeitItemProvider != null) personaFertigkeitItemProvider.dispose();
        if (personaFertigkeitsGruppeItemProvider != null) personaFertigkeitsGruppeItemProvider.dispose();
        if (cyberwareItemProvider != null) cyberwareItemProvider.dispose();
        if (bioWareItemProvider != null) bioWareItemProvider.dispose();
        if (mudanPersonaItemProvider != null) mudanPersonaItemProvider.dispose();
        if (kiKraftItemProvider != null) kiKraftItemProvider.dispose();
        if (speziesItemProvider != null) speziesItemProvider.dispose();
        if (kiAdeptItemProvider != null) kiAdeptItemProvider.dispose();
        if (kleidungItemProvider != null) kleidungItemProvider.dispose();
        if (fernkampfwaffeModifikatorItemProvider != null) fernkampfwaffeModifikatorItemProvider.dispose();
        if (personaEigenschaftItemProvider != null) personaEigenschaftItemProvider.dispose();
        if (magierItemProvider != null) magierItemProvider.dispose();
        if (mysticAdeptItemProvider != null) mysticAdeptItemProvider.dispose();
        if (personaZauberItemProvider != null) personaZauberItemProvider.dispose();
        if (zauberItemProvider != null) zauberItemProvider.dispose();
        if (aspektMagierItemProvider != null) aspektMagierItemProvider.dispose();
        if (schutzgeistItemProvider != null) schutzgeistItemProvider.dispose();
        if (initationItemProvider != null) initationItemProvider.dispose();
        if (metaMagieItemProvider != null) metaMagieItemProvider.dispose();
        if (critterKraftItemProvider != null) critterKraftItemProvider.dispose();
        if (bodenfahrzeugItemProvider != null) bodenfahrzeugItemProvider.dispose();
        if (passagierFahrzeugItemProvider != null) passagierFahrzeugItemProvider.dispose();
        if (drohneItemProvider != null) drohneItemProvider.dispose();
        if (fahrzeugModifikationItemProvider != null) fahrzeugModifikationItemProvider.dispose();
        if (technomancerItemProvider != null) technomancerItemProvider.dispose();
        if (komplexeFormItemProvider != null) komplexeFormItemProvider.dispose();
        if (personaKomplexFormItemProvider != null) personaKomplexFormItemProvider.dispose();
        if (spriteItemProvider != null) spriteItemProvider.dispose();
        if (echoItemProvider != null) echoItemProvider.dispose();
        if (vertragItemProvider != null) vertragItemProvider.dispose();
        if (lifestyleItemProvider != null) lifestyleItemProvider.dispose();
        if (wissensfertigkeitItemProvider != null) wissensfertigkeitItemProvider.dispose();
        if (sprachfertigkeitItemProvider != null) sprachfertigkeitItemProvider.dispose();
        if (critterItemProvider != null) critterItemProvider.dispose();
        if (sinItemProvider != null) sinItemProvider.dispose();
        if (lizenzItemProvider != null) lizenzItemProvider.dispose();
        if (credstickItemProvider != null) credstickItemProvider.dispose();
        if (munitionItemProvider != null) munitionItemProvider.dispose();
        if (gebundenerGeistItemProvider != null) gebundenerGeistItemProvider.dispose();
        if (geistItemProvider != null) geistItemProvider.dispose();
        if (credstickTransactionItemProvider != null) credstickTransactionItemProvider.dispose();
        if (spezialisierungItemProvider != null) spezialisierungItemProvider.dispose();
        if (commlinkItemProvider != null) commlinkItemProvider.dispose();
        if (cyberdeckItemProvider != null) cyberdeckItemProvider.dispose();
        if (programItemProvider != null) programItemProvider.dispose();
        if (softwareAgentItemProvider != null) softwareAgentItemProvider.dispose();
        if (hostItemProvider != null) hostItemProvider.dispose();
        if (riggerCommandConsoleItemProvider != null) riggerCommandConsoleItemProvider.dispose();
    }

}
