<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="runtime" nsURI="http://urszeidler.de/shr5/runtime/1.0" nsPrefix="runtime">
  <eClassifiers xsi:type="ecore:EEnum" name="Zustand">
    <eLiterals name="ok"/>
    <eLiterals name="betaeubt" value="1"/>
    <eLiterals name="sterbend" value="2"/>
    <eLiterals name="tot" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendetData">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Is the key of the extendetData Map."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eFeature" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enviorment" eSuperTypes="#//AbstractExtendetDataAware"/>
  <eClassifiers xsi:type="ecore:EClass" name="NahkampModifikationen" abstract="true"
      interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Contains the close combat modification types."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chracterIsDown" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enemyCloseCombat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characterRunning" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="characterProne" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendetDataAware" abstract="true" interface="true">
    <eOperations name="addToExtendetData">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="add a value to the extendet data store"/>
      </eAnnotations>
      <eParameters name="data" eType="#//ExtendetData"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="getIntegerValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="return an integer value or null"/>
      </eAnnotations>
      <eParameters name="data" eType="#//ExtendetData"/>
    </eOperations>
    <eOperations name="increaseValue">
      <eParameters name="data" eType="#//ExtendetData"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="decreaseValue">
      <eParameters name="data" eType="#//ExtendetData"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="hasValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="data" eType="#//ExtendetData"/>
    </eOperations>
    <eOperations name="addToList">
      <eParameters name="data" eType="#//ExtendetData"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="addUniqueToList">
      <eParameters name="data" eType="#//ExtendetData"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="getListValue">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="data" eType="#//ExtendetData"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extendetData" lowerBound="1"
        transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="#//ExtendetData"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhyicalState" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="physicalDamage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mentalDamage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zustand" eType="#//Zustand"
        defaultValueLiteral="ok"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overDead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeCharacter" eSuperTypes="#//AbstractExtendetDataAware #//PhyicalState">
    <eOperations name="canUseEdge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Simple method to decide if the character has edge left."/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="character" lowerBound="1"
        eType="ecore:EClass ../../de.urszeidler.shr5.management.model/model/shr5Management.ecore#//ManagedCharacter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightHand" eType="ecore:EClass ../../de.urszeidler.shr5.model/model/shr5.ecore#//AbstraktGegenstand"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftHand" eType="ecore:EClass ../../de.urszeidler.shr5.model/model/shr5.ecore#//AbstraktGegenstand"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inUse" upperBound="-1"
        eType="ecore:EClass ../../de.urszeidler.shr5.model/model/shr5.ecore#//AbstraktGegenstand"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="armor" eType="ecore:EClass ../../de.urszeidler.shr5.model/model/shr5.ecore#//Kleidung"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usedEdge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Counts the edge used."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Team" eSuperTypes="../../de.urszeidler.shr5.model/model/shr5.ecore#//Beschreibbar">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//RuntimeCharacter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractExtendetDataAware" abstract="true"
      eSuperTypes="#//ExtendetDataAware"/>
  <eClassifiers xsi:type="ecore:EClass" name="GruntTeam" eSuperTypes="#//Team">
    <eOperations name="buildMembers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gruntGroup" lowerBound="1"
        eType="ecore:EClass ../../de.urszeidler.shr5.management.model/model/shr5Management.ecore#//GruntGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GruntRuntimeCharacter" eSuperTypes="#//RuntimeCharacter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle" abstract="true" eSuperTypes="#//AbstractExtendetDataAware">
    <eTypeParameters name="V">
      <eBounds eClassifier="ecore:EClass ../../de.urszeidler.shr5.model/model/shr5.ecore#//Fahrzeug"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" lowerBound="1">
      <eGenericType eTypeParameter="#//Vehicle/V"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vehicleCondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modus" eType="ecore:EEnum ../../de.urszeidler.shr5.model/model/shr5.ecore#//InterfaceModus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentSpeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Drone">
    <eGenericSuperTypes eClassifier="#//Vehicle">
      <eTypeArguments eClassifier="ecore:EClass ../../de.urszeidler.shr5.model/model/shr5.ecore#//Drohne"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixDevice">
    <eTypeParameters name="M">
      <eBounds eClassifier="ecore:EClass ../../de.urszeidler.shr5.model/model/shr5.ecore#//MatrixDevice"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" lowerBound="1">
      <eGenericType eTypeParameter="#//MatrixDevice/M"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matrixCondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="marks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RiggerConsole">
    <eGenericSuperTypes eClassifier="#//MatrixDevice">
      <eTypeArguments eClassifier="ecore:EClass ../../de.urszeidler.shr5.model/model/shr5.ecore#//RiggerCommandConsole"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cyberdeck">
    <eGenericSuperTypes eClassifier="#//MatrixDevice">
      <eTypeArguments eClassifier="ecore:EClass ../../de.urszeidler.shr5.model/model/shr5.ecore#//Cyberdeck"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
